/**
 * HTTP Contracts package - shared API contract definitions.
 *
 * This package provides:
 * - OpenAPI schema definitions for IntexuraOS APIs
 * - Fastify JSON Schemas for route validation
 * - Reusable schema patterns across services
 */

// OpenAPI schemas for swagger configuration
export {
  ERROR_CODES,
  ErrorCodeSchema,
  DiagnosticsSchema,
  ErrorBodySchema,
  ApiOkSchema,
  ApiErrorSchema,
  HealthCheckSchema,
  HealthResponseSchema,
  coreComponentSchemas,
  contractComponentSchemas,
  bearerAuthSecurityScheme,
} from './openapi-schemas.js';

// Fastify schemas for route validation
export {
  fastifyDiagnosticsSchema,
  fastifyErrorCodeSchema,
  fastifyErrorBodySchema,
  contractFastifySchemas,
  registerCoreSchemas,
} from './fastify-schemas.js';

export {
  bookmarksBookmarkResponseSchema,
  bookmarksBookmarkSchema,
  bookmarksCreateBookmarkDataSchema,
  bookmarksCreateBookmarkRequestSchema,
  bookmarksCreateBookmarkResponseSchema,
  imageGenerateImageRequestSchema,
  imageGenerateImageResponseSchema,
  imageGeneratePromptRequestSchema,
  imageGeneratePromptResponseSchema,
  imageGeneratedImageDataSchema,
  imageThumbnailPromptSchema,
  notesCreateNoteRequestSchema,
  notesCreateNoteResponseSchema,
  notionPagePreviewResponseSchema,
  notionPagePreviewSchema,
  notionTokenContextResponseSchema,
  notionTokenContextSchema,
  researchCreateDraftRequestSchema,
  researchCreateDraftResponseSchema,
  calendarCreateEventDataSchema,
  calendarCreateEventInputSchema,
  calendarCreateEventRequestSchema,
  calendarCreateEventResponseSchema,
  calendarCreatedEventSchema,
  calendarEventDateTimeSchema,
  calendarProcessActionRequestSchema,
  calendarProcessActionResponseSchema,
  calendarPreviewSchema,
  calendarPreviewDataSchema,
  calendarPreviewEnvelopeSchema,
  calendarPreviewResponseSchema,
  calendarGeneratePreviewRequestSchema,
  linearProcessActionRequestSchema,
  linearProcessActionResponseSchema,
  serviceFeedbackZodSchema,
  webAgentFetchLinkPreviewsRequestSchema,
  webAgentFetchLinkPreviewsResponseSchema,
  webAgentLinkPreviewMetadataSchema,
  webAgentLinkPreviewResultSchema,
  webAgentLinkPreviewSchema,
  webAgentPageSummaryMetadataSchema,
  webAgentPageSummaryResultSchema,
  webAgentPageSummarySchema,
  webAgentSummarizePageRequestSchema,
  webAgentSummarizePageResponseSchema,
  type BookmarksBookmark,
  type BookmarksCreateBookmarkData,
  type BookmarksCreateBookmarkRequest,
  type ImageGeneratedImageData,
  type ImageGenerateImageRequest,
  type ImageGeneratePromptRequest,
  type ImageThumbnailPrompt,
  type NotesCreateNoteRequest,
  type NotionPagePreview,
  type NotionTokenContext,
  type ResearchCreateDraftRequest,
  type CalendarCreateEventData,
  type CalendarCreateEventInput,
  type CalendarCreateEventRequest,
  type CalendarCreateEventResponse,
  type CalendarCreatedEvent,
  type CalendarEventDateTime,
  type CalendarProcessActionRequest,
  type CalendarPreview,
  type CalendarPreviewData,
  type CalendarPreviewEnvelope,
  type CalendarPreviewResponse,
  type CalendarGeneratePreviewRequest,
  type LinearProcessActionRequest,
  type WebAgentFetchLinkPreviewsData,
  type WebAgentFetchLinkPreviewsRequest,
  type WebAgentLinkPreview,
  type WebAgentPageSummary,
  type WebAgentSummarizePageData,
  type WebAgentSummarizePageRequest,
} from './zod/index.js';
