import type { Actionability, WebhookEventGroup } from './models.js';

export interface RuleEvaluationInput {
  eventGroup: WebhookEventGroup;
  action: string | null;
  senderLogin: string;
  senderAllowed: boolean;
  body: string | null;
  hasExistingTask: boolean;
}

export interface RuleEvaluationResult {
  actionability: Actionability;
  reasonCode: string;
  confidence: number;
  reasoning: string;
}

const ACTIONABLE_PR_ACTIONS = new Set(['opened', 'synchronize', 'reopened']);

const REVIEW_ACTIONS = new Set(['submitted']);

const BOT_NOISE_PATTERNS: readonly RegExp[] = [
  /^##\s*coverage\s*report/i,
  /^\+1$/,
  /^👍$/,
  /^\s*lgtm\s*$/i,
  /\[codecov\]/i,
  /\[coveralls\]/i,
  /generated by \[/i,
  /^bumps \[/i,
];

const BOT_SENDER_PATTERNS: readonly RegExp[] = [
  /dependabot\[bot\]/i,
  /renovate\[bot\]/i,
  /snyk-bot/i,
];

function isBotNoise(body: string, senderLogin: string): boolean {
  const trimmed = body.trim();
  for (const pattern of BOT_NOISE_PATTERNS) {
    if (pattern.test(trimmed)) return true;
  }
  for (const pattern of BOT_SENDER_PATTERNS) {
    if (pattern.test(senderLogin)) return true;
  }
  return false;
}

/**
 * Rule evaluation order (most specific / cheapest first):
 *
 * 1. Sender not allowed → non_actionable
 * 2. Unsupported event group → non_actionable
 * 3. Bot noise detection → non_actionable
 * 4. Empty body on comment events → non_actionable
 * 5. Obvious PR actions (opened/synchronize) → actionable
 * 6. Review submitted with body → actionable
 * 7. Everything else → uncertain (triggers planner)
 */
export function evaluateWebhookActionabilityRules(
  input: RuleEvaluationInput
): RuleEvaluationResult {
  if (!input.senderAllowed) {
    return {
      actionability: 'non_actionable',
      reasonCode: 'sender_not_allowed',
      confidence: 1.0,
      reasoning: `Sender '${input.senderLogin}' is not on the allowlist`,
    };
  }

  if (input.eventGroup === 'other' || input.eventGroup === 'github_action_result') {
    return {
      actionability: 'non_actionable',
      reasonCode: 'unsupported_event_group',
      confidence: 1.0,
      reasoning: `Event group '${input.eventGroup}' is not supported for actionability`,
    };
  }

  if (input.body !== null && input.body.length > 0 && isBotNoise(input.body, input.senderLogin)) {
    return {
      actionability: 'non_actionable',
      reasonCode: 'bot_noise',
      confidence: 0.95,
      reasoning: 'Comment body matches known bot noise pattern',
    };
  }

  if (input.eventGroup === 'comment' && (input.body === null || input.body.length === 0)) {
    return {
      actionability: 'non_actionable',
      reasonCode: 'empty_body',
      confidence: 1.0,
      reasoning: 'Comment event with empty body is not actionable',
    };
  }

  if (input.eventGroup === 'pull_request') {
    if (input.action !== null && ACTIONABLE_PR_ACTIONS.has(input.action)) {
      return {
        actionability: 'actionable',
        reasonCode: `pr_${input.action}`,
        confidence: 0.95,
        reasoning: `PR action '${input.action}' is directly actionable`,
      };
    }

    if (input.action !== null && REVIEW_ACTIONS.has(input.action) && input.body !== null && input.body.length > 0) {
      return {
        actionability: 'actionable',
        reasonCode: 'review_submitted',
        confidence: 0.9,
        reasoning: 'Review submitted with body content is actionable',
      };
    }
  }

  return {
    actionability: 'uncertain',
    reasonCode: 'needs_planner',
    confidence: 0.5,
    reasoning: 'No deterministic rule matched; requires planner evaluation',
  };
}
