import { describe, it, expect } from 'vitest';
import {
  evaluateWebhookActionabilityRules,
  type RuleEvaluationInput,
} from '../../../domain/githubWebhookAgent/rules.js';

function makeInput(overrides: Partial<RuleEvaluationInput> = {}): RuleEvaluationInput {
  return {
    eventGroup: 'comment',
    action: 'created',
    senderLogin: 'pbuchman',
    senderAllowed: true,
    body: 'Please fix the login bug',
    hasExistingTask: true,
    ...overrides,
  };
}

describe('evaluateWebhookActionabilityRules', () => {
  describe('sender disallowed', () => {
    it('returns non_actionable for disallowed sender', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ senderAllowed: false })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('sender_not_allowed');
      expect(result.confidence).toBeGreaterThanOrEqual(0.9);
    });
  });

  describe('unsupported event group', () => {
    it('returns non_actionable for other event group', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ eventGroup: 'other' })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('unsupported_event_group');
      expect(result.confidence).toBeGreaterThanOrEqual(0.9);
    });

    it('returns non_actionable for github_action_result event group', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ eventGroup: 'github_action_result' })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('unsupported_event_group');
    });
  });

  describe('bot noise detection', () => {
    it('returns non_actionable for coverage report body', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ body: '## Coverage Report\n\n| File | Lines | Branches |\n|---|---|---|' })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('bot_noise');
    });

    it('returns non_actionable for "+1" comment', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ body: '+1' })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('bot_noise');
    });

    it('returns non_actionable for thumbs up emoji only', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ body: '👍' })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('bot_noise');
    });

    it('returns non_actionable for bot linkback text', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({
          body: 'This comment was generated by [codecov](https://codecov.io). Please review.',
        })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('bot_noise');
    });

    it('returns non_actionable for dependabot PR body', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({
          body: 'Bumps [lodash](https://github.com/lodash/lodash) from 4.17.20 to 4.17.21.\n\n**Release notes**',
          senderLogin: 'dependabot[bot]',
          senderAllowed: true,
        })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('bot_noise');
    });

    it('returns non_actionable for bot sender with non-noise body', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({
          body: 'Updated dependencies in package.json',
          senderLogin: 'renovate[bot]',
          senderAllowed: true,
        })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('bot_noise');
    });
  });

  describe('empty body handling', () => {
    it('returns non_actionable for null body on comment', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ body: null, eventGroup: 'comment' })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('empty_body');
    });

    it('returns non_actionable for empty string body on comment', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ body: '', eventGroup: 'comment' })
      );
      expect(result.actionability).toBe('non_actionable');
      expect(result.reasonCode).toBe('empty_body');
    });

    it('allows null body for pull_request events', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ body: null, eventGroup: 'pull_request', action: 'opened' })
      );
      expect(result.actionability).not.toBe('non_actionable');
    });
  });

  describe('obvious actionable cases', () => {
    it('returns actionable for PR opened event', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ eventGroup: 'pull_request', action: 'opened', body: 'Add login feature' })
      );
      expect(result.actionability).toBe('actionable');
      expect(result.reasonCode).toBe('pr_opened');
      expect(result.confidence).toBeGreaterThanOrEqual(0.8);
    });

    it('returns actionable for PR synchronize event', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ eventGroup: 'pull_request', action: 'synchronize', body: null })
      );
      expect(result.actionability).toBe('actionable');
      expect(result.reasonCode).toBe('pr_synchronize');
    });

    it('returns actionable for review submitted with body', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({
          eventGroup: 'pull_request',
          action: 'submitted',
          body: 'Please address the security concern in the auth handler.',
        })
      );
      expect(result.actionability).toBe('actionable');
      expect(result.reasonCode).toBe('review_submitted');
    });
  });

  describe('uncertain / ambiguous cases', () => {
    it('returns uncertain for human comment without explicit task instruction', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({
          body: 'Interesting approach, I wonder if this will scale.',
        })
      );
      expect(result.actionability).toBe('uncertain');
      expect(result.reasonCode).toBe('needs_planner');
      expect(result.confidence).toBeLessThan(0.8);
    });

    it('returns uncertain for PR closed event', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ eventGroup: 'pull_request', action: 'closed', body: null })
      );
      expect(result.actionability).toBe('uncertain');
      expect(result.reasonCode).toBe('needs_planner');
    });

    it('returns uncertain for unknown action on pull_request', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({ eventGroup: 'pull_request', action: 'labeled', body: null })
      );
      expect(result.actionability).toBe('uncertain');
      expect(result.reasonCode).toBe('needs_planner');
    });

    it('returns uncertain for edited issue_comment from bot', () => {
      const result = evaluateWebhookActionabilityRules(
        makeInput({
          eventGroup: 'comment',
          action: 'edited',
          senderLogin: 'claude[bot]',
          body: 'Updated review feedback.',
        })
      );
      expect(result.actionability).toBe('uncertain');
      expect(result.reasonCode).toBe('needs_planner');
    });
  });

  describe('determinism', () => {
    it('returns identical results for identical inputs', () => {
      const input = makeInput();
      const a = evaluateWebhookActionabilityRules(input);
      const b = evaluateWebhookActionabilityRules(input);
      expect(a).toEqual(b);
    });
  });
});
