#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ID="${PROJECT_ID:-intexuraos-dev-pbuchman}"
REGION="${REGION:-europe-central2}"
OUTPUT_FILE="${OUTPUT_FILE:-/etc/intexuraos/.env.prod}"
PROVISIONER_SA_KEY_FILE="${PROVISIONER_SA_KEY_FILE:-${GOOGLE_APPLICATION_CREDENTIALS:-/home/deploy/provisioner-sa-key.json}}"
RUNTIME_SA_KEY_FILE="${RUNTIME_SA_KEY_FILE:-/home/deploy/runtime-sa-key.json}"
INTERNAL_AUTH_TOKEN_FILE="${INTERNAL_AUTH_TOKEN_FILE:-/etc/intexuraos/internal-auth-token}"
PUBLIC_ORIGIN="${PUBLIC_ORIGIN:-https://intexuraos.cloud}"
DEPLOY_USER="${DEPLOY_USER:-deploy}"
NGINX_TOKEN_GROUP="${NGINX_TOKEN_GROUP:-www-data}"
TEMP_ENV_FILE=""

declare -a REQUESTED_SECRETS=()
HETZNER_RUNTIME_SECRETS=(
  INTEXURAOS_AUTH0_CLIENT_ID
  INTEXURAOS_AUTH0_DOMAIN
  INTEXURAOS_AUTH0_SPA_CLIENT_ID
  INTEXURAOS_AUTH_AUDIENCE
  INTEXURAOS_AUTH_ISSUER
  INTEXURAOS_AUTH_JWKS_URL
  INTEXURAOS_CLOUDFLARE_ACCOUNT_ID
  INTEXURAOS_CLOUDFLARE_API_TOKEN
  INTEXURAOS_ENCRYPTION_KEY
  INTEXURAOS_FIREBASE_API_KEY
  INTEXURAOS_FIREBASE_AUTH_DOMAIN
  INTEXURAOS_FIREBASE_PROJECT_ID
  INTEXURAOS_GEMINI_APP_API_KEY
  INTEXURAOS_GRAFANA_CLOUD_LOKI_TOKEN
  INTEXURAOS_GRAFANA_CLOUD_LOKI_URL
  INTEXURAOS_GRAFANA_CLOUD_LOKI_USERNAME
  INTEXURAOS_GITHUB_OAUTH_CLIENT_ID
  INTEXURAOS_GITHUB_OAUTH_CLIENT_SECRET
  INTEXURAOS_GITHUB_WEBHOOK_SECRET
  INTEXURAOS_GOOGLE_OAUTH_CLIENT_ID
  INTEXURAOS_GOOGLE_OAUTH_CLIENT_SECRET
  INTEXURAOS_GOOGLE_OAUTH_REDIRECT_URI
  INTEXURAOS_GUEST_SESSION_SECRET
  INTEXURAOS_INTERNAL_AUTH_TOKEN
  INTEXURAOS_OPENAI_APP_API_KEY
  INTEXURAOS_OPENROUTER_APP_API_KEY
  INTEXURAOS_ORCHESTRATOR_SECRET
  INTEXURAOS_SENTRY_DSN
  INTEXURAOS_SENTRY_DSN_WEB
  INTEXURAOS_TOKEN_ENCRYPTION_KEY
  INTEXURAOS_WEBHOOK_VERIFY_SECRET
  INTEXURAOS_WHATSAPP_ACCESS_TOKEN
  INTEXURAOS_WHATSAPP_APP_SECRET
  INTEXURAOS_WHATSAPP_PHONE_NUMBER_ID
  INTEXURAOS_WHATSAPP_VERIFY_TOKEN
  INTEXURAOS_WHATSAPP_WABA_ID
)

usage() {
  printf 'Usage: INTEXURAOS_ENVIRONMENT=prod %s [--output path] [--project-id id] [--secret NAME]\n' "$(basename "$0")"
}

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

cleanup_temp_file() {
  if [[ -n "${TEMP_ENV_FILE:-}" ]]; then
    rm -f "${TEMP_ENV_FILE}"
  fi
}

require_prod() {
  if [[ "${INTEXURAOS_ENVIRONMENT:-}" != "prod" ]]; then
    fail "Refusing to load secrets unless INTEXURAOS_ENVIRONMENT=prod"
  fi
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --output)
        shift
        [[ $# -gt 0 ]] || fail "--output requires a value"
        OUTPUT_FILE="$1"
        shift
        ;;
      --output=*)
        OUTPUT_FILE="${1#*=}"
        shift
        ;;
      --project-id)
        shift
        [[ $# -gt 0 ]] || fail "--project-id requires a value"
        PROJECT_ID="$1"
        shift
        ;;
      --project-id=*)
        PROJECT_ID="${1#*=}"
        shift
        ;;
      --secret)
        shift
        [[ $# -gt 0 ]] || fail "--secret requires a value"
        REQUESTED_SECRETS+=("$1")
        shift
        ;;
      --secret=*)
        REQUESTED_SECRETS+=("${1#*=}")
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        fail "Unknown argument: $1"
        ;;
    esac
  done
}

load_secret_names() {
  if [[ ${#REQUESTED_SECRETS[@]} -gt 0 ]]; then
    printf '%s\n' "${REQUESTED_SECRETS[@]}" | sort -u
    return
  fi

  printf '%s\n' "${HETZNER_RUNTIME_SECRETS[@]}" | sort -u
}

validate_secret_name() {
  local secret_name="$1"

  if [[ ! "${secret_name}" =~ ^INTEXURAOS_[A-Z0-9_]+$ ]]; then
    fail "Invalid Secret Manager name: ${secret_name}"
  fi
}

dotenv_escape() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  value="${value//$'\r'/\\r}"
  printf '"%s"' "${value}"
}

write_env_line() {
  local output_path="$1"
  local key="$2"
  local value="$3"

  printf '%s=%s\n' "${key}" "$(dotenv_escape "${value}")" >> "${output_path}"
}

write_header() {
  local output_path="$1"

  cat > "${output_path}" <<HEADER
# Generated by scripts/hetzner/load-secrets.sh.
# Do not edit by hand. Values are sourced from GCP Secret Manager.
HEADER
  write_env_line "${output_path}" "INTEXURAOS_ENVIRONMENT" "prod"
  write_env_line "${output_path}" "INTEXURAOS_RUNTIME" "prod"
  write_env_line "${output_path}" "INTEXURAOS_GCP_PROJECT_ID" "${PROJECT_ID}"
  write_env_line "${output_path}" "GOOGLE_CLOUD_PROJECT" "${PROJECT_ID}"
  write_env_line "${output_path}" "PROJECT_ID" "${PROJECT_ID}"
  write_env_line "${output_path}" "REGION" "${REGION}"
  write_env_line "${output_path}" "HETZNER_PROVISIONER_GOOGLE_APPLICATION_CREDENTIALS" "${PROVISIONER_SA_KEY_FILE}"
  write_env_line "${output_path}" "GOOGLE_APPLICATION_CREDENTIALS" "${RUNTIME_SA_KEY_FILE}"
  write_env_line "${output_path}" "INTEXURAOS_PUBLIC_ORIGIN" "${PUBLIC_ORIGIN}"
  write_env_line "${output_path}" "INTEXURAOS_WEB_APP_URL" "${PUBLIC_ORIGIN}"
  write_env_line "${output_path}" "INTEXURAOS_WEB_URL" "${PUBLIC_ORIGIN}"
  write_env_line "${output_path}" "INTEXURAOS_CODE_TASK_CALLBACK_BASE_URL" "${PUBLIC_ORIGIN}"
  write_env_line "${output_path}" "NODE_ENV" "production"
}

read_secret() {
  local secret_name="$1"

  gcloud secrets versions access latest \
    --secret="${secret_name}" \
    --project="${PROJECT_ID}"
}

install_internal_auth_token() {
  local token="$1"
  local temp_file=""

  temp_file="$(mktemp "${TMPDIR:-/tmp}/intexuraos-internal-auth.XXXXXX")"
  printf '%s' "${token}" > "${temp_file}"

  getent group "${NGINX_TOKEN_GROUP}" >/dev/null 2>&1 \
    || fail "Group ${NGINX_TOKEN_GROUP} is required before writing ${INTERNAL_AUTH_TOKEN_FILE}"

  install -d -m 755 "$(dirname "${INTERNAL_AUTH_TOKEN_FILE}")"
  install -m 640 -o root -g "${NGINX_TOKEN_GROUP}" "${temp_file}" "${INTERNAL_AUTH_TOKEN_FILE}"
  rm -f "${temp_file}"
}

append_secret() {
  local output_path="$1"
  local secret_name="$2"
  local secret_value=""

  validate_secret_name "${secret_name}"

  printf 'Loading secret %s\n' "${secret_name}" >&2
  if ! secret_value="$(read_secret "${secret_name}")"; then
    fail "Unable to read Secret Manager value for ${secret_name}"
  fi

  write_env_line "${output_path}" "${secret_name}" "${secret_value}"

  if [[ "${secret_name}" == "INTEXURAOS_INTERNAL_AUTH_TOKEN" ]]; then
    install_internal_auth_token "${secret_value}"
  fi
}

main() {
  parse_args "$@"
  require_prod

  command -v gcloud >/dev/null 2>&1 || fail "gcloud CLI is required"
  id -u "${DEPLOY_USER}" >/dev/null 2>&1 || fail "Deploy user ${DEPLOY_USER} is required"

  if [[ -r "${PROVISIONER_SA_KEY_FILE}" ]]; then
    export CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE="${PROVISIONER_SA_KEY_FILE}"
  fi

  umask 077

  local temp_file=""
  TEMP_ENV_FILE="$(mktemp "${TMPDIR:-/tmp}/intexuraos-prod-env.XXXXXX")"
  temp_file="${TEMP_ENV_FILE}"
  trap cleanup_temp_file EXIT

  mapfile -t secret_names < <(load_secret_names)
  [[ ${#secret_names[@]} -gt 0 ]] || fail "No secrets selected"

  write_header "${temp_file}"

  local secret_name=""
  for secret_name in "${secret_names[@]}"; do
    append_secret "${temp_file}" "${secret_name}"
  done

  install -d -m 755 "$(dirname "${OUTPUT_FILE}")"
  install -m 600 -o "${DEPLOY_USER}" -g "${DEPLOY_USER}" "${temp_file}" "${OUTPUT_FILE}"

  printf 'Wrote %s with %s secrets (mode 600)\n' "${OUTPUT_FILE}" "${#secret_names[@]}"
  printf 'Wrote %s for nginx internal-auth injection\n' "${INTERNAL_AUTH_TOKEN_FILE}"
}

main "$@"
