#!/bin/bash
# Generated by cc-statusline v1.4.0 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2026-01-22T09:09:53.064Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, tokens, burnrate
STATUSLINE_VERSION="1.4.0"

input=$(cat)

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
api_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;222m'; fi; }   # warm gold
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }


# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- API endpoint detection ----
api_endpoint=""

# Try to extract from JSON input first (if Claude Code provides it)
if [ "$HAS_JQ" -eq 1 ]; then
  api_endpoint=$(echo "$input" | jq -r '.api_base_url // .apiBaseUrl // .api_endpoint // ""' 2>/dev/null)
else
  api_endpoint=$(echo "$input" | grep -o '"api_base_url"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"api_base_url"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$api_endpoint" ] && api_endpoint=$(echo "$input" | grep -o '"apiBaseUrl"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"apiBaseUrl"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# Fall back to environment variables
if [ -z "$api_endpoint" ] || [ "$api_endpoint" = "null" ]; then
  api_endpoint="${ANTHROPIC_BASE_URL:-${ANTHROPIC_API_BASE:-}}"
fi

# Parse the endpoint to show a friendly name
api_display=""
api_bg_color=""  # Background color for special APIs
if [ -n "$api_endpoint" ] && [ "$api_endpoint" != "null" ]; then
  # Extract host from URL for display (remove protocol and path)
  api_host=$(echo "$api_endpoint" | sed -E 's|^https?://||' | cut -d'/' -f1)

  # Special handling for known APIs
  if [ "$api_host" = "api.z.ai" ]; then
    api_display="Z.AI"
    api_bg_color="47"  # White background
  elif [ "$api_host" = "api.anthropic.com" ]; then
    api_display="anthropic"
    api_bg_color="48;5;208"  # Orange background
  else
    api_display="$api_host"
  fi
else
  api_display="anthropic"
  api_bg_color="48;5;208"  # Orange background for default Anthropic
fi

# ---- Model override for api.z.ai ----
# Store original api_host for model override logic
if [ -n "$api_endpoint" ] && [ "$api_endpoint" != "null" ]; then
  stored_api_host=$(echo "$api_endpoint" | sed -E 's|^https?://||' | cut -d'/' -f1)
else
  stored_api_host="api.anthropic.com"
fi

# Override model display when using api.z.ai
if [ "$stored_api_host" = "api.z.ai" ]; then
  model_name="GLM 4.7"
  model_version=""  # Clear version for cleaner display
fi

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- git ----
git_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
  if [ ${#git_branch} -gt 20 ]; then
    git_branch="${git_branch:0:17}..."
  fi
fi

# ---- context window calculation (native) ----
context_used_pct=""
token_metrics=""
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # default mint green
token_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; }  # light gray

if [ "$HAS_JQ" -eq 1 ]; then
  CONTEXT_SIZE=$(echo "$input" | jq -r '.context_window.context_window_size // 200000' 2>/dev/null)

  # Cumulative session totals
  TOTAL_INPUT=$(echo "$input" | jq -r '.context_window.total_input_tokens // 0' 2>/dev/null)
  TOTAL_OUTPUT=$(echo "$input" | jq -r '.context_window.total_output_tokens // 0' 2>/dev/null)

  # Per-request cache metrics
  USAGE=$(echo "$input" | jq '.context_window.current_usage' 2>/dev/null)
  if [ "$USAGE" != "null" ] && [ -n "$USAGE" ]; then
    CACHE_CREATION=$(echo "$USAGE" | jq '.cache_creation_input_tokens // 0' 2>/dev/null)
    CACHE_READ=$(echo "$USAGE" | jq '.cache_read_input_tokens // 0' 2>/dev/null)
  else
    CACHE_CREATION=0
    CACHE_READ=0
  fi

  if [ "$TOTAL_INPUT" -gt 0 ] 2>/dev/null; then
    # Calculate context % from current_usage (accurate for context window)
    if [ "$USAGE" != "null" ] && [ -n "$USAGE" ]; then
      INPUT_TOKENS=$(echo "$USAGE" | jq '.input_tokens // 0' 2>/dev/null)
      CURRENT_TOKENS=$((INPUT_TOKENS + CACHE_CREATION + CACHE_READ))
      context_used_pct=$(( CURRENT_TOKENS * 100 / CONTEXT_SIZE ))
      (( context_used_pct < 0 )) && context_used_pct=0
      (( context_used_pct > 100 )) && context_used_pct=100
    fi

    # Set color based on used percentage (higher = worse)
    if [ "$context_used_pct" -ge 80 ]; then
      context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
    elif [ "$context_used_pct" -ge 60 ]; then
      context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
    fi

    # Format with k for thousands
    fmt_k() {
      local n="$1"
      if [ "$n" -ge 1000 ]; then
        echo "$((n / 1000))k"
      else
        echo "$n"
      fi
    }

    token_metrics="📊 $(token_color)↓$(fmt_k $TOTAL_INPUT) ↑$(fmt_k $TOTAL_OUTPUT) +$(fmt_k $CACHE_CREATION) ⚡$(fmt_k $CACHE_READ)$(rst)"
  fi
fi

# ---- hook metrics (executed + blocked commands) ----
hook_metrics=""
hooks_dir=""

# Find hooks directory - try CLAUDE_PROJECT_DIR first, then current_dir
if [ -n "$CLAUDE_PROJECT_DIR" ] && [ -d "$CLAUDE_PROJECT_DIR/.claude/hooks" ]; then
  hooks_dir="$CLAUDE_PROJECT_DIR/.claude/hooks"
elif [ -d ".claude/hooks" ]; then
  hooks_dir=".claude/hooks"
fi

if [ -n "$hooks_dir" ]; then
  # Count session commands (from session-commands.log, cleared at session start)
  session_cmds=0
  if [ -f "$hooks_dir/session-commands.log" ]; then
    session_cmds=$(wc -l < "$hooks_dir/session-commands.log" 2>/dev/null | tr -d ' ' || echo 0)
  fi

  # Count session blocked (from session-blocked.log, cleared at session start)
  session_blocked=0
  if [ -f "$hooks_dir/session-blocked.log" ]; then
    session_blocked=$(wc -l < "$hooks_dir/session-blocked.log" 2>/dev/null | tr -d ' ' || echo 0)
  fi

  # Count total blocked (cumulative from hooks.log)
  total_blocked=0
  if [ -f "$hooks_dir/hooks.log" ]; then
    total_blocked=$(grep -c "BLOCKED" "$hooks_dir/hooks.log" 2>/dev/null || echo 0)
  fi

  # Show metrics if any activity exists
  if [ "$session_cmds" -gt 0 ] || [ "$session_blocked" -gt 0 ] || [ "$total_blocked" -gt 0 ]; then
    # Calculate session block rate percentage
    session_total=$((session_cmds + session_blocked))
    if [ "$session_total" -gt 0 ]; then
      session_pct=$((session_blocked * 100 / session_total))
    else
      session_pct=0
    fi
    hook_metrics="🛡️ ✓${session_cmds} ✗${session_blocked} (${session_pct}%) | ✗${total_blocked} total"
  fi
fi


# ---- render statusline ----
# Line 1: Core info (directory, git, model, claude code version, output style)
printf '📁 %s%s%s' "$(dir_color)" "$current_dir" "$(rst)"
if [ -n "$git_branch" ]; then
  printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
fi
printf '  🤖 %s%s%s' "$(model_color)" "$model_name" "$(rst)"
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  printf '  🏷️ %s%s%s' "$(version_color)" "$model_version" "$(rst)"
fi
if [ -n "$cc_version" ] && [ "$cc_version" != "null" ]; then
  printf '  📟 %sv%s%s' "$(cc_version_color)" "$cc_version" "$(rst)"
fi

# Line 2: Context and hook metrics
line2=""
if [ -n "$context_used_pct" ]; then
  line2="🧠 $(context_color)${context_used_pct}%$(rst)"
else
  line2="🧠 $(context_color)-$(rst)"
fi
if [ -n "$hook_metrics" ]; then
  line2="$line2  $hook_metrics"
fi
if [ -n "$token_metrics" ]; then
  line2="$line2  $token_metrics"
fi

# MEGA session stats (append to line2, only if session matches)
mega_sessions_file="$HOME/.make-english-great-again/sessions.json"
if [ -f "$mega_sessions_file" ] && [ -n "$session_id" ]; then
  mega_total=$(jq -r --arg sid "$session_id" '.sessions[] | select(.session_id == $sid) | .total // 0' "$mega_sessions_file" 2>/dev/null)
  mega_saved=$(jq -r --arg sid "$session_id" '.sessions[] | select(.session_id == $sid) | .saved // 0' "$mega_sessions_file" 2>/dev/null)
  if [ -n "$mega_total" ] && [ "$mega_total" != "null" ] && [ "$mega_total" -gt 0 ] 2>/dev/null; then
    mega_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;183m'; fi; }
    line2="$line2  📝 $(mega_color)MEGA: ${mega_saved}/${mega_total}$(rst)"
  fi
fi

# Line 3: Port metrics and load average
# Get all 3 load averages (1min, 5min, 15min)
load_avg=$(uptime | sed -E 's/.*load averages?: ([0-9.]+)[, ]+([0-9.]+)[, ]+([0-9.]+).*/\1 \2 \3/')
if command -v free >/dev/null 2>&1; then
  mem_usage=$(free -m | awk '/^Mem:/ { printf "%.1fG/%.1fG", $3/1024, $2/1024 }')
else
  mem_total_bytes=$(sysctl -n hw.memsize 2>/dev/null)
  mem_pages_active=$(vm_stat 2>/dev/null | awk '/Pages active/ { gsub(/\./,"",$3); print $3 }')
  mem_pages_wired=$(vm_stat 2>/dev/null | awk '/Pages wired/ { gsub(/\./,"",$4); print $4 }')
  mem_pages_compressed=$(vm_stat 2>/dev/null | awk '/Pages occupied by compressor/ { gsub(/\./,"",$5); print $5 }')
  mem_used_bytes=$(( (${mem_pages_active:-0} + ${mem_pages_wired:-0} + ${mem_pages_compressed:-0}) * 4096 ))
  mem_usage=$(awk "BEGIN { printf \"%.1fG/%.1fG\", ${mem_used_bytes}/1073741824, ${mem_total_bytes:-0}/1073741824 }")
fi
load_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; }  # light gray
hostname=$(uname -n)
hostname_display="$hostname"
if [ "$use_color" -eq 1 ]; then
  if [ "$hostname" = "home-dev" ]; then
    hostname_display=$(printf '\033[30;48;5;150m %s \033[0m' "$hostname")
  elif [ "$hostname" = "KHKW970X6K" ]; then
    hostname_display=$(printf '\033[30;48;5;7m mac-dev \033[0m')
  fi
fi
# Build API segment for line 3 (before hostname)
api_segment=""
if [ -n "$api_display" ]; then
  if [ -n "$api_bg_color" ]; then
    if [ "$api_bg_color" = "47" ]; then
      api_segment=$(printf '🌐 \033[30;%sm %s \033[0m  ' "$api_bg_color" "$api_display")
    else
      api_segment=$(printf '🌐 \033[97;%sm %s \033[0m  ' "$api_bg_color" "$api_display")
    fi
  else
    api_segment=$(printf '🌐 %s%s%s  ' "$(api_color)" "$api_display" "$(rst)")
  fi
fi
line3="${api_segment}📈 ${hostname_display} $(load_color)${load_avg}  🧮 ${mem_usage}$(rst)"

# Line 4: Cost and usage analytics (optional)
line4=""
if [ -n "$cost_usd" ] && [[ "$cost_usd" =~ ^[0-9.]+$ ]]; then
  if [ -n "$cost_per_hour" ] && [[ "$cost_per_hour" =~ ^[0-9.]+$ ]]; then
    cost_per_hour_formatted=$(printf '%.2f' "$cost_per_hour")
    line4="💰 $(cost_color)\$$(printf '%.2f' "$cost_usd")$(rst) ($(burn_color)\$${cost_per_hour_formatted}/h$(rst))"
  else
    line4="💰 $(cost_color)\$$(printf '%.2f' "$cost_usd")$(rst)"
  fi
fi
if [ -n "$tot_tokens" ] && [[ "$tot_tokens" =~ ^[0-9]+$ ]]; then
  if [ -n "$tpm" ] && [[ "$tpm" =~ ^[0-9.]+$ ]]; then
    tpm_formatted=$(printf '%.0f' "$tpm")
    if [ -n "$line4" ]; then
      line4="$line4  📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
    else
      line4="📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
    fi
  else
    if [ -n "$line4" ]; then
      line4="$line4  📊 $(usage_color)${tot_tokens} tok$(rst)"
    else
      line4="📊 $(usage_color)${tot_tokens} tok$(rst)"
    fi
  fi
fi

# Print lines
if [ -n "$line2" ]; then
  printf '\n%s' "$line2"
fi
if [ -n "$line3" ]; then
  printf '\n%s' "$line3"
fi
if [ -n "$line4" ]; then
  printf '\n%s' "$line4"
fi
printf '\n'
