#!/bin/bash
# Generated by cc-statusline v1.4.0 (https://www.npmjs.com/package/@chongdashu/cc-statusline)
# Custom Claude Code statusline - Created: 2026-01-22T09:09:53.064Z
# Theme: detailed | Colors: true | Features: directory, git, model, context, usage, tokens, burnrate
STATUSLINE_VERSION="1.4.0"

# Debug logging - writes to file when statusline is called
DEBUG_LOG="$HOME/.claude-statusline-debug.log"
echo "$(date '+%Y-%m-%d %H:%M:%S') - statusline.sh called, pwd=$(pwd)" >> "$DEBUG_LOG"

# Trap errors to log them
trap 'echo "$(date '+%Y-%m-%d %H:%M:%S') - ERROR at line $LINENO: $BASH_COMMAND" >> "$DEBUG_LOG"' ERR

input=$(cat)

# Log whether we got input
if [ -z "$input" ]; then
  echo "$(date '+%Y-%m-%d %H:%M:%S') - WARNING: Empty input received" >> "$DEBUG_LOG"
else
  echo "$(date '+%Y-%m-%d %H:%M:%S') - Input received, length=${#input}" >> "$DEBUG_LOG"
fi

# ---- check jq availability ----
HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

# ---- color helpers (force colors for Claude Code) ----
use_color=1
[ -n "$NO_COLOR" ] && use_color=0

C() { if [ "$use_color" -eq 1 ]; then printf '\033[%sm' "$1"; fi; }
RST() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- modern sleek colors ----
dir_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;117m'; fi; }    # sky blue
model_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;147m'; fi; }  # light purple
version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;180m'; fi; } # soft yellow
cc_version_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;249m'; fi; } # light gray
style_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;245m'; fi; } # gray
api_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;222m'; fi; }   # warm gold
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- time helpers ----
to_epoch() {
  ts="$1"
  if command -v gdate >/dev/null 2>&1; then gdate -d "$ts" +%s 2>/dev/null && return; fi
  date -u -j -f "%Y-%m-%dT%H:%M:%S%z" "${ts/Z/+0000}" +%s 2>/dev/null && return
  python3 - "$ts" <<'PY' 2>/dev/null
import sys, datetime
s=sys.argv[1].replace('Z','+00:00')
print(int(datetime.datetime.fromisoformat(s).timestamp()))
PY
}

fmt_time_hm() {
  epoch="$1"
  if date -r 0 +%s >/dev/null 2>&1; then date -r "$epoch" +"%H:%M"; else date -d "@$epoch" +"%H:%M"; fi
}

progress_bar() {
  pct="${1:-0}"; width="${2:-10}"
  [[ "$pct" =~ ^[0-9]+$ ]] || pct=0; ((pct<0))&&pct=0; ((pct>100))&&pct=100
  filled=$(( pct * width / 100 )); empty=$(( width - filled ))
  printf '%*s' "$filled" '' | tr ' ' '='
  printf '%*s' "$empty" '' | tr ' ' '-'
}

# git utilities
num_or_zero() { v="$1"; [[ "$v" =~ ^[0-9]+$ ]] && echo "$v" || echo 0; }

# ---- JSON extraction utilities ----
# Pure bash JSON value extractor (fallback when jq not available)
extract_json_string() {
  local json="$1"
  local key="$2"
  local default="${3:-}"
  
  # For nested keys like workspace.current_dir, get the last part
  local field="${key##*.}"
  field="${field%% *}"  # Remove any jq operators
  
  # Try to extract string value (quoted)
  local value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" | head -1 | sed 's/.*:[[:space:]]*"\([^"]*\)".*/\1/')
  
  # Convert escaped backslashes to forward slashes for Windows paths
  if [ -n "$value" ]; then
    value=$(echo "$value" | sed 's/\\\\/\//g')
  fi
  
  # If no string value found, try to extract number value (unquoted)
  if [ -z "$value" ] || [ "$value" = "null" ]; then
    value=$(echo "$json" | grep -o "\"\${field}\"[[:space:]]*:[[:space:]]*[0-9.]\+" | head -1 | sed 's/.*:[[:space:]]*\([0-9.]\+\).*/\1/')
  fi
  
  # Return value or default
  if [ -n "$value" ] && [ "$value" != "null" ]; then
    echo "$value"
  else
    echo "$default"
  fi
}

# ---- basics ----
if [ "$HAS_JQ" -eq 1 ]; then
  current_dir=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // "unknown"' 2>/dev/null | sed "s|^$HOME|~|g")
  model_name=$(echo "$input" | jq -r '.model.display_name // "Claude"' 2>/dev/null)
  model_version=$(echo "$input" | jq -r '.model.version // ""' 2>/dev/null)
  session_id=$(echo "$input" | jq -r '.session_id // ""' 2>/dev/null)
  cc_version=$(echo "$input" | jq -r '.version // ""' 2>/dev/null)
  output_style=$(echo "$input" | jq -r '.output_style.name // ""' 2>/dev/null)
else
  # Bash fallback for JSON extraction
  # Extract current_dir from workspace object - look for the pattern workspace":{"current_dir":"..."}
  current_dir=$(echo "$input" | grep -o '"workspace"[[:space:]]*:[[:space:]]*{[^}]*"current_dir"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"current_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  
  # Fall back to cwd if workspace extraction failed
  if [ -z "$current_dir" ] || [ "$current_dir" = "null" ]; then
    current_dir=$(echo "$input" | grep -o '"cwd"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' | sed 's/\\\\/\//g')
  fi
  
  # Fallback to unknown if all extraction failed
  [ -z "$current_dir" ] && current_dir="unknown"
  current_dir=$(echo "$current_dir" | sed "s|^$HOME|~|g")
  
  # Extract model name from nested model object
  model_name=$(echo "$input" | grep -o '"model"[[:space:]]*:[[:space:]]*{[^}]*"display_name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"display_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$model_name" ] && model_name="Claude"
  # Model version is in the model ID, not a separate field  
  model_version=""  # Not available in Claude Code JSON
  session_id=$(extract_json_string "$input" "session_id" "")
  # CC version is at the root level
  cc_version=$(echo "$input" | grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  # Output style is nested
  output_style=$(echo "$input" | grep -o '"output_style"[[:space:]]*:[[:space:]]*{[^}]*"name"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# ---- API endpoint detection ----
api_endpoint=""

# Try to extract from JSON input first (if Claude Code provides it)
if [ "$HAS_JQ" -eq 1 ]; then
  api_endpoint=$(echo "$input" | jq -r '.api_base_url // .apiBaseUrl // .api_endpoint // ""' 2>/dev/null)
else
  api_endpoint=$(echo "$input" | grep -o '"api_base_url"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"api_base_url"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
  [ -z "$api_endpoint" ] && api_endpoint=$(echo "$input" | grep -o '"apiBaseUrl"[[:space:]]*:[[:space:]]*"[^"]*"' | sed 's/.*"apiBaseUrl"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/')
fi

# Fall back to environment variables
if [ -z "$api_endpoint" ] || [ "$api_endpoint" = "null" ]; then
  api_endpoint="${ANTHROPIC_BASE_URL:-${ANTHROPIC_API_BASE:-}}"
fi

# Parse the endpoint to show a friendly name
api_display=""
if [ -n "$api_endpoint" ] && [ "$api_endpoint" != "null" ]; then
  # Extract host from URL for display (remove protocol and path)
  api_host=$(echo "$api_endpoint" | sed -E 's|^https?://||' | cut -d'/' -f1)
  api_display="$api_host"
else
  api_display="api.anthropic.com"
fi

# ---- git colors ----
git_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;150m'; fi; }  # soft green
rst() { if [ "$use_color" -eq 1 ]; then printf '\033[0m'; fi; }

# ---- git ----
git_branch=""
if git rev-parse --git-dir >/dev/null 2>&1; then
  git_branch=$(git branch --show-current 2>/dev/null || git rev-parse --short HEAD 2>/dev/null)
fi

# ---- context window calculation (native) ----
context_used_pct=""
context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;158m'; fi; }  # default mint green

if [ "$HAS_JQ" -eq 1 ]; then
  CONTEXT_SIZE=$(echo "$input" | jq -r '.context_window.context_window_size // 200000' 2>/dev/null)
  USAGE=$(echo "$input" | jq '.context_window.current_usage' 2>/dev/null)

  if [ "$USAGE" != "null" ] && [ -n "$USAGE" ]; then
    CURRENT_TOKENS=$(echo "$USAGE" | jq '(.input_tokens // 0) + (.cache_creation_input_tokens // 0) + (.cache_read_input_tokens // 0)' 2>/dev/null)

    if [ -n "$CURRENT_TOKENS" ] && [ "$CURRENT_TOKENS" -gt 0 ] 2>/dev/null; then
      context_used_pct=$(( CURRENT_TOKENS * 100 / CONTEXT_SIZE ))
      # Clamp to valid range
      (( context_used_pct < 0 )) && context_used_pct=0
      (( context_used_pct > 100 )) && context_used_pct=100

      # Set color based on used percentage (higher = worse)
      if [ "$context_used_pct" -ge 80 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;203m'; fi; }  # coral red
      elif [ "$context_used_pct" -ge 60 ]; then
        context_color() { if [ "$use_color" -eq 1 ]; then printf '\033[38;5;215m'; fi; }  # peach
      fi
    fi
  fi
fi

# ---- hook metrics (executed + blocked commands) ----
hook_metrics=""
hooks_dir=""

# Find hooks directory - try CLAUDE_PROJECT_DIR first, then current_dir
if [ -n "$CLAUDE_PROJECT_DIR" ] && [ -d "$CLAUDE_PROJECT_DIR/.claude/hooks" ]; then
  hooks_dir="$CLAUDE_PROJECT_DIR/.claude/hooks"
elif [ -d ".claude/hooks" ]; then
  hooks_dir=".claude/hooks"
fi

if [ -n "$hooks_dir" ]; then
  # Count executed commands
  executed=0
  if [ -f "$hooks_dir/commands.log" ]; then
    executed=$(grep -c "^\[" "$hooks_dir/commands.log" 2>/dev/null || echo 0)
  fi

  # Count blocked by each hook (short labels)
  b_vitest=$(grep -c "BLOCKED" "$hooks_dir/validate-vitest-flags.log" 2>/dev/null || echo 0)
  b_poll=$(grep -c "BLOCKED" "$hooks_dir/validate-polling.log" 2>/dev/null || echo 0)
  b_poll=$((b_poll + $(grep -c "BLOCKED" "$hooks_dir/validate-gh-polling.log" 2>/dev/null || echo 0)))
  b_ci=$(grep -c "BLOCKED" "$hooks_dir/validate-ci-output-capture.log" 2>/dev/null || echo 0)
  b_cov=$(grep -c "BLOCKED" "$hooks_dir/validate-coverage-commands.log" 2>/dev/null || echo 0)
  b_ws=$(grep -c "BLOCKED" "$hooks_dir/validate-verify-workspace.log" 2>/dev/null || echo 0)
  b_gcloud=$(grep -c "BLOCKED" "$hooks_dir/validate-gcloud-builds.log" 2>/dev/null || echo 0)
  b_gcloud=$((b_gcloud + $(grep -c "BLOCKED" "$hooks_dir/validate-gcloud-builds-log.log" 2>/dev/null || echo 0)))

  blocked=$((b_vitest + b_poll + b_ci + b_cov + b_ws + b_gcloud))
  total=$((executed + blocked))

  if [ "$total" -gt 0 ]; then
    # Build breakdown string (only show non-zero)
    breakdown=""
    [ "$b_vitest" -gt 0 ] && breakdown="${breakdown}vi:${b_vitest} "
    [ "$b_poll" -gt 0 ] && breakdown="${breakdown}poll:${b_poll} "
    [ "$b_ci" -gt 0 ] && breakdown="${breakdown}ci:${b_ci} "
    [ "$b_cov" -gt 0 ] && breakdown="${breakdown}cov:${b_cov} "
    [ "$b_ws" -gt 0 ] && breakdown="${breakdown}ws:${b_ws} "
    [ "$b_gcloud" -gt 0 ] && breakdown="${breakdown}gc:${b_gcloud} "
    breakdown=$(echo "$breakdown" | sed 's/ $//')

    hook_metrics="🛡️ Cmds:${total} | ✗${blocked} (${breakdown})"
  fi
fi

# ---- PM2 status ----
pm2_metrics=""
if command -v pm2 &>/dev/null || command -v npx &>/dev/null; then
  pm2_json=$(pm2 jlist 2>/dev/null || npx pm2 jlist 2>/dev/null)
  if [ -n "$pm2_json" ] && [ "$HAS_JQ" -eq 1 ]; then
    pm2_online=$(echo "$pm2_json" | jq '[.[] | select(.pm2_env.status == "online")] | length' 2>/dev/null || echo 0)
    pm2_total=$(echo "$pm2_json" | jq 'length' 2>/dev/null || echo 0)
    pm2_worktree=$(echo "$pm2_json" | jq -r '.[0].pm2_env.pm_cwd // empty' 2>/dev/null | grep -oE 'intexuraos-[0-9]+' || echo "")
    if [ "$pm2_total" -gt 0 ]; then
      wt_suffix=""
      [ -n "$pm2_worktree" ] && wt_suffix=" (${pm2_worktree})"
      if [ "$pm2_online" -eq "$pm2_total" ]; then
        pm2_metrics="⚡ PM2:${pm2_online}/${pm2_total}${wt_suffix}"
      else
        pm2_metrics="⚡ PM2:${pm2_online}/${pm2_total}${wt_suffix} ⚠️"
      fi
    fi
  fi
fi

# ---- render statusline ----
# Line 1: Core info (directory, git, model, claude code version, output style)
printf '📁 %s%s%s' "$(dir_color)" "$current_dir" "$(rst)"
if [ -n "$git_branch" ]; then
  printf '  🌿 %s%s%s' "$(git_color)" "$git_branch" "$(rst)"
fi
printf '  🤖 %s%s%s' "$(model_color)" "$model_name" "$(rst)"
if [ -n "$model_version" ] && [ "$model_version" != "null" ]; then
  printf '  🏷️ %s%s%s' "$(version_color)" "$model_version" "$(rst)"
fi
if [ -n "$cc_version" ] && [ "$cc_version" != "null" ]; then
  printf '  📟 %sv%s%s' "$(cc_version_color)" "$cc_version" "$(rst)"
fi
if [ -n "$api_display" ]; then
  printf '  🌐 %s%s%s' "$(api_color)" "$api_display" "$(rst)"
fi

# Line 2: Context and hook metrics (same line)
line2=""
if [ -n "$context_used_pct" ]; then
  line2="🧠 $(context_color)CTX ${context_used_pct}%$(rst)"
else
  line2="🧠 $(context_color)CTX -$(rst)"
fi
if [ -n "$hook_metrics" ]; then
  line2="$line2  $hook_metrics"
fi
if [ -n "$pm2_metrics" ]; then
  line2="$line2  $pm2_metrics"
fi

# ---- Orchestrator port check ----
if lsof -i :8199 -sTCP:LISTEN >/dev/null 2>&1; then
  line2="$line2  🎭 Orch:✓"
else
  line2="$line2  🎭 Orch:✗"
fi

# Line 3: Cost and usage analytics
line3=""
if [ -n "$cost_usd" ] && [[ "$cost_usd" =~ ^[0-9.]+$ ]]; then
  if [ -n "$cost_per_hour" ] && [[ "$cost_per_hour" =~ ^[0-9.]+$ ]]; then
    cost_per_hour_formatted=$(printf '%.2f' "$cost_per_hour")
    line3="💰 $(cost_color)\$$(printf '%.2f' "$cost_usd")$(rst) ($(burn_color)\$${cost_per_hour_formatted}/h$(rst))"
  else
    line3="💰 $(cost_color)\$$(printf '%.2f' "$cost_usd")$(rst)"
  fi
fi
if [ -n "$tot_tokens" ] && [[ "$tot_tokens" =~ ^[0-9]+$ ]]; then
  if [ -n "$tpm" ] && [[ "$tpm" =~ ^[0-9.]+$ ]]; then
    tpm_formatted=$(printf '%.0f' "$tpm")
    if [ -n "$line3" ]; then
      line3="$line3  📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
    else
      line3="📊 $(usage_color)${tot_tokens} tok (${tpm_formatted} tpm)$(rst)"
    fi
  else
    if [ -n "$line3" ]; then
      line3="$line3  📊 $(usage_color)${tot_tokens} tok$(rst)"
    else
      line3="📊 $(usage_color)${tot_tokens} tok$(rst)"
    fi
  fi
fi

# Print lines
if [ -n "$line2" ]; then
  printf '\n%s' "$line2"
fi
if [ -n "$line3" ]; then
  printf '\n%s' "$line3"
fi
printf '\n'

echo "$(date '+%Y-%m-%d %H:%M:%S') - statusline.sh completed successfully" >> "$DEBUG_LOG"
