import { loadRequiredEnv } from './__shims__/common-worker.js';

const env = loadRequiredEnv({
  INTEXURAOS_GCP_PROJECT_ID: { required: true },
  INTEXURAOS_VM_ZONE: { required: true },
  INTEXURAOS_VM_INSTANCE_NAME: { required: true },
  INTEXURAOS_VM_HEALTH_URL: { required: true },
  INTEXURAOS_VM_SHUTDOWN_URL: { required: true },
});

export const VM_CONFIG = {
  PROJECT_ID: env.INTEXURAOS_GCP_PROJECT_ID,
  ZONE: env.INTEXURAOS_VM_ZONE,
  INSTANCE_NAME: env.INTEXURAOS_VM_INSTANCE_NAME,
  HEALTH_ENDPOINT: env.INTEXURAOS_VM_HEALTH_URL,
  SHUTDOWN_ENDPOINT: env.INTEXURAOS_VM_SHUTDOWN_URL,

  HEALTH_POLL_INTERVAL_MS: 10_000,
  HEALTH_POLL_TIMEOUT_MS: 180_000,
  SHUTDOWN_GRACE_PERIOD_MS: 600_000,
  SHUTDOWN_POLL_INTERVAL_MS: 30_000,
  ORCHESTRATOR_UNRESPONSIVE_TIMEOUT_MS: 120_000,
} as const;
