/**
 * Service for mirroring code task status to actions.
 * Ensures Inbox UI shows accurate task progress.
 *
 * Design doc: docs/designs/INT-156-code-action-type.md (lines 309-348)
 */

import type { Logger } from '@intexuraos/common-core';
import type { ActionsAgentClient } from '../clients/actionsAgentClient.js';
import type { TaskStatus } from '../../domain/models/codeTask.js';

/**
 * Status of the associated resource (e.g., code task).
 * Must match actions-agent's ResourceStatus type exactly.
 * See: apps/actions-agent/src/domain/models/action.ts
 */
export type ResourceStatus =
  | 'dispatched'
  | 'running'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'interrupted';

export interface StatusMirrorServiceDeps {
  actionsAgentClient: ActionsAgentClient;
  logger: Logger;
}

export interface StatusMirrorService {
  /**
   * Mirror code task status to the corresponding action.
   * Non-fatal: failures are logged but don't stop task execution.
   */
  mirrorStatus(params: {
    actionId: string | undefined;
    taskStatus: TaskStatus;
    resourceUrl?: string;
    errorMessage?: string;
    traceId?: string;
  }): Promise<void>;
}

/**
 * UUID v4 format validation.
 * Real actions-agent IDs are standard UUIDs (crypto.randomUUID()).
 * Synthetic patterns (webhook-assign-*, pr-comment/*, merge-conflict/*, fanout_*) don't match.
 */
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isRealActionId(actionId: string): boolean {
  return UUID_REGEX.test(actionId);
}

export function createStatusMirrorService(deps: StatusMirrorServiceDeps): StatusMirrorService {
  const { actionsAgentClient, logger } = deps;

  // Map TaskStatus → ResourceStatus (actions-agent vocabulary)
  // 'planned'/'implemented' both map to 'completed' for the Inbox UI
  const statusMapping: Record<TaskStatus, ResourceStatus> = {
    queued: 'dispatched',       // Queued maps to dispatched for Inbox UI (INT-619)
    dispatched: 'dispatched',
    running: 'running',
    planned: 'completed',
    implemented: 'completed',
    reviewed: 'completed',
    failed: 'failed',
    cancelled: 'cancelled',
    interrupted: 'interrupted',
    archived: 'completed',     // Archived tasks treated as completed for Inbox UI (INT-711)
  };

  return {
    async mirrorStatus(params): Promise<void> {
      const { actionId, taskStatus, resourceUrl, errorMessage, traceId } = params;

      if (actionId === undefined) {
        logger.debug({ taskStatus }, 'Skipping status mirror (no actionId)');
        return;
      }

      // Guard: skip status mirror for synthetic actionIds (non-UUID patterns).
      // These are generated by non-actions-agent flows for dedup purposes only.
      // See: INT-1119
      if (!isRealActionId(actionId)) {
        logger.debug({ actionId, taskStatus }, 'Skipping status mirror (synthetic actionId)');
        return;
      }

      const resourceStatus = statusMapping[taskStatus];
      const result = await actionsAgentClient.updateActionStatus(
        actionId,
        resourceStatus,
        resourceUrl !== undefined ? { prUrl: resourceUrl } : errorMessage !== undefined ? { error: errorMessage } : undefined,
        traceId
      );

      if (!result.ok) {
        logger.warn(
          { actionId, taskStatus, error: result.error },
          'Failed to mirror status to action'
        );
      }
    },
  };
}
