#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

PROJECT_ID="${PROJECT_ID:-intexuraos-dev-pbuchman}"
OUTPUT_FILE="${OUTPUT_FILE:-/etc/intexuraos/grafana-cloud.env}"
GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS:-/home/pbuchman/.config/gcloud/sa-key.json}"
INTEXURAOS_ENVIRONMENT="${INTEXURAOS_ENVIRONMENT:-dev}"
TEMP_ENV_FILE=""

GRAFANA_CLOUD_COLLECTOR_SECRETS=(
  INTEXURAOS_GRAFANA_CLOUD_LOKI_TOKEN
  INTEXURAOS_GRAFANA_CLOUD_LOKI_URL
  INTEXURAOS_GRAFANA_CLOUD_LOKI_USERNAME
)

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

cleanup() {
  [[ -n "${TEMP_ENV_FILE}" ]] && rm -f "${TEMP_ENV_FILE}"
}

dotenv_escape() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  value="${value//$'\r'/\\r}"
  printf '"%s"' "${value}"
}

write_env_line() {
  local output_path="$1"
  local key="$2"
  local value="$3"

  printf '%s=%s\n' "${key}" "$(dotenv_escape "${value}")" >> "${output_path}"
}

require_gcloud() {
  command -v gcloud >/dev/null 2>&1 || fail "gcloud is required"

  if [[ -f "${GOOGLE_APPLICATION_CREDENTIALS}" ]]; then
    gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}" --project="${PROJECT_ID}" >/dev/null
  fi
}

read_secret() {
  local secret_name="$1"
  gcloud secrets versions access latest --secret="${secret_name}" --project="${PROJECT_ID}"
}

main() {
  trap cleanup EXIT

  if [[ "${INTEXURAOS_ENVIRONMENT}" != "dev" ]]; then
    fail "load-grafana-cloud-env.sh is for home-dev; use scripts/hetzner/load-secrets.sh for prod"
  fi

  require_gcloud
  TEMP_ENV_FILE="$(mktemp "${TMPDIR:-/tmp}/grafana-cloud-env.XXXXXX")"

  cat > "${TEMP_ENV_FILE}" <<HEADER
# Generated by scripts/observability/load-grafana-cloud-env.sh.
# Do not edit by hand. Values are sourced from GCP Secret Manager.
HEADER
  write_env_line "${TEMP_ENV_FILE}" "INTEXURAOS_ENVIRONMENT" "dev"

  for secret_name in "${GRAFANA_CLOUD_COLLECTOR_SECRETS[@]}"; do
    write_env_line "${TEMP_ENV_FILE}" "${secret_name}" "$(read_secret "${secret_name}")"
  done

  install -d -m 755 "$(dirname "${OUTPUT_FILE}")"
  install -m 600 -o root -g root "${TEMP_ENV_FILE}" "${OUTPUT_FILE}"
  printf 'Wrote Grafana Cloud collector environment to %s\n' "${OUTPUT_FILE}"
}

main "$@"
