#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
RUNTIME_CONFIG_RENDERER="${REPO_ROOT}/scripts/render-runtime-config.mjs"
PROJECT_ID="${PROJECT_ID:-intexuraos-dev-pbuchman}"
OUTPUT_FILE="${OUTPUT_FILE:-/etc/intexuraos/grafana-cloud.env}"
GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS:-/home/pbuchman/.config/gcloud/sa-key.json}"
INTEXURAOS_ENVIRONMENT="${INTEXURAOS_ENVIRONMENT:-dev}"
TEMP_ENV_FILE=""

GRAFANA_CLOUD_COLLECTOR_SECRETS=(
  INTEXURAOS_GRAFANA_CLOUD_LOKI_TOKEN
)

GRAFANA_CLOUD_COLLECTOR_CONFIG=(
  INTEXURAOS_GRAFANA_CLOUD_LOKI_URL
  INTEXURAOS_GRAFANA_CLOUD_LOKI_USERNAME
)

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

cleanup() {
  [[ -n "${TEMP_ENV_FILE}" ]] && rm -f "${TEMP_ENV_FILE}"
}

dotenv_escape() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  value="${value//$'\r'/\\r}"
  printf '"%s"' "${value}"
}

write_env_line() {
  local output_path="$1"
  local key="$2"
  local value="$3"

  printf '%s=%s\n' "${key}" "$(dotenv_escape "${value}")" >> "${output_path}"
}

require_gcloud() {
  command -v gcloud >/dev/null 2>&1 || fail "gcloud is required"

  if [[ -f "${GOOGLE_APPLICATION_CREDENTIALS}" ]]; then
    gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}" --project="${PROJECT_ID}" >/dev/null
  fi
}

read_secret() {
  local secret_name="$1"
  gcloud secrets versions access latest --secret="${secret_name}" --project="${PROJECT_ID}"
}

main() {
  trap cleanup EXIT

  if [[ "${INTEXURAOS_ENVIRONMENT}" != "dev" ]]; then
    fail "load-grafana-cloud-env.sh is for home-dev; use scripts/hetzner/load-secrets.sh for prod"
  fi

  require_gcloud
  command -v node >/dev/null 2>&1 || fail "node is required for runtime configuration"
  umask 077
  TEMP_ENV_FILE="$(mktemp "${TMPDIR:-/tmp}/grafana-cloud-env.XXXXXX")"

  cat > "${TEMP_ENV_FILE}" <<HEADER
# Generated by scripts/observability/load-grafana-cloud-env.sh.
# Do not edit by hand. Values are merged from tracked config and GCP Secret Manager.
HEADER
  write_env_line "${TEMP_ENV_FILE}" "INTEXURAOS_ENVIRONMENT" "dev"

  local config_args=()
  local config_name=""
  for config_name in "${GRAFANA_CLOUD_COLLECTOR_CONFIG[@]}"; do
    config_args+=(--key "${config_name}")
  done
  if ! node "${RUNTIME_CONFIG_RENDERER}" \
    --environment dev \
    --format dotenv \
    "${config_args[@]}" >> "${TEMP_ENV_FILE}"
  then
    fail "Unable to render tracked Grafana Cloud configuration"
  fi

  local secret_name=""
  local secret_value=""
  for secret_name in "${GRAFANA_CLOUD_COLLECTOR_SECRETS[@]}"; do
    if ! secret_value="$(read_secret "${secret_name}")"; then
      fail "Unable to read Secret Manager value for ${secret_name}"
    fi
    [[ -n "${secret_value}" ]] || fail "Secret Manager value is empty for ${secret_name}"
    write_env_line "${TEMP_ENV_FILE}" "${secret_name}" "${secret_value}"
  done

  install -d -m 755 "$(dirname "${OUTPUT_FILE}")"
  install -m 600 -o root -g root "${TEMP_ENV_FILE}" "${OUTPUT_FILE}"
  printf 'Wrote Grafana Cloud collector environment to %s\n' "${OUTPUT_FILE}"
}

main "$@"
